### ISSUE TITLE
Oak does not build with rustc 1.21.0-nightly (c11f689d2 2017-08-29)

### ISSUE THREAD

**Issue by berkus** [ptal/oak#103]
Compiling oak v0.5.3
error[E0425]: cannot find function `word` in module `rust::pp`
  --> /Users/berkus/.cargo/registry/src/github.com-1ecc6299db9ec823/oak-0.5.3/src/liboak/back/code_printer.rs:59:17
   |
59 |       rust::pp::word(&mut s.s, ";")?;
   |                 ^^^^ not found in `rust::pp`

error[E0063]: missing field `span` in initializer of `syntax::ast::AngleBracketedParameterData`
   --> /Users/berkus/.cargo/registry/src/github.com-1ecc6299db9ec823/oak-0.5.3/src/liboak/ast.rs:131:7
    |
131 |       AngleBracketedParameterData {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `span`

error[E0599]: no method named `is_any_keyword` found for type `syntax::parse::token::Token` in the current scope
   --> /Users/berkus/.cargo/registry/src/github.com-1ecc6299db9ec823/oak-0.5.3/src/liboak/front/parser.rs:290:36
    |
290 |       rtok::Ident(ident) if !token.is_any_keyword() => {
    |                                    ^^^^^^^^^^^^^^

error[E0599]: no method named `is_any_keyword` found for type `syntax::parse::token::Token` in the current scope
   --> /Users/berkus/.cargo/registry/src/github.com-1ecc6299db9ec823/oak-0.5.3/src/liboak/front/parser.rs:415:14
    |
415 |       !token.is_any_keyword() &&
    |              ^^^^^^^^^^^^^^

error[E0063]: missing field `tokens` in initializer of `syntax::ast::Item`
  --> /Users/berkus/.cargo/registry/src/github.com-1ecc6299db9ec823/oak-0.5.3/src/liboak/back/context.rs:88:18
   |
88 |       let item = rust::Item {
   |                  ^^^^^^^^^^ missing `tokens`

error[E0063]: missing field `tokens` in initializer of `syntax::ast::Item`
  --> /Users/berkus/.cargo/registry/src/github.com-1ecc6299db9ec823/oak-0.5.3/src/liboak/back/compiler/grammar.rs:70:17
   |
70 |         rust::P(rust::Item {
   |                 ^^^^^^^^^^ missing `tokens`

**Comment by berkus** [comment]
Thanks! Confirmed to build with rustc 1.21.0-nightly (7eeac1b81 2017-08-30)
